module.exports = {
  run: [
    // Step 1: Verify Docker is installed and running
    {
      method: "shell.run",
      params: {
        message: "node check-docker.js",
      },
    },

    // Step 2: Collect API keys from user
    {
      method: "input",
      params: {
        title: "OpenVoiceUI Setup",
        description: "A free Groq key is required for voice synthesis. Get one at console.groq.com",
        form: [
          {
            key: "GROQ_API_KEY",
            title: "Groq API Key (required — Text-to-Speech)",
            description: "Free tier available at console.groq.com",
            placeholder: "gsk_...",
            required: true,
          },
          {
            key: "PORT",
            title: "Port (default: 5001)",
            placeholder: "5001",
            required: false,
          },
        ],
      },
    },

    // Step 3: Create openclaw config directory
    {
      method: "shell.run",
      params: {
        message: "{{platform === 'win32' ? 'if not exist openclaw-data mkdir openclaw-data' : 'mkdir -p openclaw-data'}}",
      },
    },

    // Step 4: Write openclaw config (nested keys for v2026.3.2+)
    {
      method: "fs.write",
      params: {
        path: "openclaw-data/openclaw.json",
        text: JSON.stringify({
          gateway: {
            mode: "local",
            port: 18791,
            bind: "lan",
            trustedProxies: ["127.0.0.1", "172.16.0.0/12", "10.0.0.0/8"],
            controlUi: {
              allowInsecureAuth: true,
              dangerouslyDisableDeviceAuth: true,
            },
          },
          agents: {
            defaults: {
              thinkingDefault: "off",
              timeoutSeconds: 120,
            },
          },
        }, null, 2),
      },
    },

    // Step 5: Write .env (local install — no auth, fixed tokens are fine)
    {
      method: "fs.write",
      params: {
        path: ".env",
        text: [
          "# OpenVoiceUI — generated by Pinokio installer",
          "PORT={{input.PORT||5001}}",
          "DOMAIN=localhost",
          "SECRET_KEY=pinokio-local-install",
          "",
          "# OpenClaw Gateway",
          "CLAWDBOT_GATEWAY_URL=ws://127.0.0.1:18791",
          "CLAWDBOT_AUTH_TOKEN=pinokio-local-token",
          "GATEWAY_SESSION_KEY=voice-main-1",
          "",
          "# TTS — Groq Orpheus",
          "GROQ_API_KEY={{input.GROQ_API_KEY}}",
          "USE_GROQ=true",
          "USE_GROQ_TTS=true",
          "",
          "# Supertonic TTS (ships with docker compose)",
          "SUPERTONIC_API_URL=http://supertonic:8765",
        ],
        join: "\n",
      },
    },

    // Step 6: Build Docker images (first run takes a few minutes)
    {
      method: "shell.run",
      params: {
        message: "docker compose -f docker-compose.yml -f docker-compose.pinokio.yml build",
      },
    },

    // Step 7: Done
    {
      method: "notify",
      params: {
        html: "OpenVoiceUI installed! Click <b>Start</b> to launch.<br><br>On first start, open <code>http://localhost:18791</code> to configure your AI provider through the OpenClaw setup wizard.",
      },
    },
  ],
}
